import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { FiMaximize2, FiVideo, FiVideoOff, FiCameraOff } from 'react-icons/fi';

export default function CameraFeed({ isActive }) {
  const [hasUserMedia, setHasUserMedia] = useState(false);
  const [stream, setStream] = useState(null);
  
  useEffect(() => {
    let videoStream = null;
    
    async function setupCamera() {
      if (!isActive) {
        if (stream) {
          stream.getTracks().forEach(track => track.stop());
          setStream(null);
        }
        setHasUserMedia(false);
        return;
      }
      
      try {
        const constraints = {
          video: {
            width: { ideal: 1280 },
            height: { ideal: 720 },
            facingMode: 'environment'
          }
        };
        
        const userMedia = await navigator.mediaDevices.getUserMedia(constraints);
        setStream(userMedia);
        setHasUserMedia(true);
        
        const videoElement = document.getElementById('camera-feed');
        if (videoElement) {
          videoElement.srcObject = userMedia;
        }
      } catch (error) {
        console.error('Error accessing camera:', error);
        setHasUserMedia(false);
      }
    }
    
    setupCamera();
    
    return () => {
      if (videoStream) {
        videoStream.getTracks().forEach(track => track.stop());
      }
    };
  }, [isActive, stream]);
  
  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5, delay: 0.1 }}
      className="glass-panel overflow-hidden"
    >
      <div className="p-4 border-b border-neutral-200 dark:border-neutral-700 flex items-center justify-between">
        <div className="flex items-center space-x-2">
          {isActive ? (
            <FiVideo className="h-5 w-5 text-success-500" />
          ) : (
            <FiVideoOff className="h-5 w-5 text-neutral-400 dark:text-neutral-500" />
          )}
          <h2 className="font-semibold text-neutral-900 dark:text-white">Live Camera Feed</h2>
        </div>
        
        <div className="flex items-center space-x-2">
          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            className="p-1.5 rounded-md text-neutral-600 dark:text-neutral-400 hover:bg-neutral-100 dark:hover:bg-neutral-800 transition-colors"
            aria-label="Fullscreen"
          >
            <FiMaximize2 className="h-4 w-4" />
          </motion.button>
        </div>
      </div>
      
      <div className="relative bg-neutral-900 aspect-video">
        {isActive ? (
          <>
            <video
              id="camera-feed"
              autoPlay
              playsInline
              muted
              className={`w-full h-full object-cover ${hasUserMedia ? 'opacity-100' : 'opacity-0'}`}
            ></video>
            
            {!hasUserMedia && (
              <div className="absolute inset-0 flex flex-col items-center justify-center text-white">
                <FiCameraOff className="h-12 w-12 mb-3 text-neutral-400" />
                <p className="text-lg font-medium text-neutral-300">Camera access required</p>
                <p className="text-sm text-neutral-400 mt-2">Please allow camera access in your browser</p>
              </div>
            )}
            
            {/* Detection overlays - these would normally be populated by AI detection results */}
            {hasUserMedia && (
              <div className="absolute inset-0 pointer-events-none">
                {/* Example detection boxes that would be generated by AI */}
                <div className="absolute left-[20%] top-[30%] w-[100px] h-[200px] border-2 border-accent-500 rounded-sm flex items-end justify-center">
                  <div className="bg-accent-500 text-white text-xs px-2 py-0.5 rounded-t-sm font-medium">
                    Person 98%
                  </div>
                </div>
                
                <div className="absolute right-[30%] top-[40%] w-[60px] h-[40px] border-2 border-error-500 rounded-sm flex items-end justify-center">
                  <div className="bg-error-500 text-white text-xs px-2 py-0.5 rounded-t-sm font-medium">
                    Weapon 92%
                  </div>
                </div>
              </div>
            )}
            
            {hasUserMedia && (
              <div className="absolute bottom-4 left-4 right-4 flex items-center justify-between">
                <div className="flex items-center space-x-2">
                  <div className="flex items-center space-x-1.5 bg-black/60 text-white text-xs py-1 px-2 rounded-md">
                    <div className="w-2 h-2 rounded-full bg-success-500"></div>
                    <span>Live</span>
                  </div>
                  <div className="bg-black/60 text-white text-xs py-1 px-2 rounded-md">
                    Source: Main Entrance
                  </div>
                </div>
                
                <div className="bg-black/60 text-white text-xs py-1 px-2 rounded-md flex items-center">
                  <span className="animate-pulse inline-block w-2 h-2 bg-secondary-500 rounded-full mr-1.5"></span>
                  AI Processing
                </div>
              </div>
            )}
          </>
        ) : (
          <div className="absolute inset-0 flex flex-col items-center justify-center text-white">
            <FiVideoOff className="h-12 w-12 mb-3 text-neutral-400" />
            <p className="text-lg font-medium text-neutral-300">Surveillance Paused</p>
            <p className="text-sm text-neutral-400 mt-2">Press the Start button to begin monitoring</p>
          </div>
        )}
      </div>
    </motion.div>
  );
}